"""Command registration tables for mobile_openclaw_cli.

Owns: low-risk argparse command metadata that does not need runtime state.
Non-goals: command execution, permission checks, queue mutation, or repair logic.
State behavior: read-only constants and parser registration only.
Normal callers: mobile_openclaw_cli.build_parser.
"""

from __future__ import annotations

import argparse


SIMPLE_CHECK_COMMANDS: tuple[tuple[str, str], ...] = (
    ("maintenance-misjudgment-boundary-check", "Run temp-only maintenance evidence freshness and plugin misjudgment regression check"),
    ("control-receipt-contract-check", "Run temp-only mobile control reply receipt contract regression check"),
    ("mobile-repair-command-entry-check", "Run temp-only mobile repair command entry regression check"),
    ("mobile-repair-specialized-modes-check", "Run temp-only mobile repair specialized mode regression check"),
    ("mobile-execution-contract-check", "Run temp-only mobile delegation execute-before-result prompt contract check"),
    ("mobile-permission-prompt-compact-check", "Run temp-only compact mobile permission prompt regression check"),
    ("stability-check", "Read-only low-noise bridge and dependency health summary"),
    ("p0-audit", "Read-only P0 event-noise and reply-backlog audit"),
    ("gui-automation-health-check", "Run temp-only GUI automation health command regression check"),
    ("onboarding-check", "Run temp-only auto thread onboarding regression checks"),
    ("account-onboarding-sync-check", "Run temp-only OpenClaw account onboarding sync regression checks"),
    ("account-onboarding-worker-lifecycle-check", "Run temp-only worker account onboarding lifecycle regression checks"),
    ("result-ownership-check", "Run temp-only result ownership regression checks"),
    ("fair-scheduling-check", "Run temp-only route fairness regression checks"),
    ("waiting-redelivery-gate-route-fairness-check", "Run temp-only waiting-redelivery gate route fairness regression check"),
    ("route-fallback-dispatch-check", "Run temp-only failed-route fallback dispatch regression check"),
    ("route-rotation-fairness-check", "Run temp-only route rotation fairness regression checks"),
    ("active-slot-release-check", "Run temp-only active route release regression checks"),
    ("same-route-expired-active-order-check", "Run temp-only expired active same-route ordering regression checks"),
    ("active-generation-supplement-check", "Run temp-only active generation supplement regression checks"),
    ("cdp-live-listener-probe-unstable-check", "Run temp-only CDP live-listener probe regression checks"),
    ("cdp-localhost-host-preserved-check", "Run temp-only CDP localhost host preservation regression checks"),
    ("active-recovery-route-fairness-check", "Run temp-only active recovery route fairness regression checks"),
    ("active-ack-inprogress-observation-check", "Run temp-only acked active turn observation regression checks"),
    ("waiting-followup-owned-result-recovery-check", "Run temp-only parked primary owned-result recovery regression check"),
    ("waiting-followup-owned-result-redelivery-gate-check", "Run temp-only parked primary owned-result redelivery gate regression check"),
    ("base-ack-only-terminal-redelivery-check", "Run temp-only base ack-only terminal redelivery regression check"),
    ("failure-close-owned-result-recovery-check", "Run temp-only failure-close owned-result recovery split regression check"),
    ("historical-failed-result-filter-check", "Run temp-only historical failed-result recovery filter regression check"),
    ("failed-result-audit-recovery-consistency-check", "Run temp-only failed-result audit/recovery consistency regression check"),
    ("protocol-violation-no-owned-result-check", "Run temp-only terminal protocol violation recovery regression check"),
    ("active-stalled-tool-recovery-check", "Run temp-only stalled quick-tool recovery regression check"),
    ("app-server-repair-continuation-check", "Run temp-only app-server no-result repair continuation regression matrix"),
    ("active-progress-observability-check", "Run temp-only active progress observation regression checks"),
    ("active-observation-diagnosis-check", "Run temp-only active observation diagnosis regression checks"),
    ("app-server-result-poll-second-chance-check", "Run temp-only app-server result poll cold-start regression check"),
    ("app-server-turn-materialization-window-check", "Run temp-only app-server turn materialization notFound regression check"),
    ("historical-owned-result-fallback-check", "Run temp-only historical mobile result-code fallback regression check"),
    ("thread-history-owned-result-fallback-check", "Run temp-only Codex thread-history owned-result fallback regression check"),
    ("thread-busy-status-check", "Run temp-only app-server thread busy status regression checks"),
    ("primary-visible-cdp-probe-failure-check", "Run temp-only primary visible CDP probe failure regression checks"),
    ("transient-health-recovery-check", "Run temp-only transient health recovery regression checks"),
    ("global-transient-health-scope-check", "Run temp-only global transient health scope regression checks"),
    ("reply-pending-account-scope-check", "Run temp-only reply pending account scope regression checks"),
    ("reply-pending-fresh-context-only-check", "Run temp-only reply pending fresh-context retry regression checks"),
    ("thread-prewarm-budget-check", "Run temp-only thread prewarm budget regression checks"),
    ("thread-unlisted-recoverable-dispatch-check", "Run temp-only healthy unlisted thread dispatch regression checks"),
    ("thread-dispatch-probe-fallback-check", "Run temp-only dispatch probe fallback regression checks"),
    ("thread-prewarm-execution-check", "Run temp-only notLoaded thread prewarm execution regression checks"),
    ("thread-prewarm-probe-failed-check", "Run temp-only transient probe failure no-prewarm regression checks"),
    ("thread-probe-failed-worker-retreat-check", "Run temp-only worker probe_failed bounded-retreat regression check"),
    ("cdp-route-quick-check", "Read-only fast CDP TCP and /json/version route probe"),
    ("cdp-visible-delivery-check", "Run temp-only CDP visible delivery regression checks"),
    ("visible-cdp-unconfirmed-observation-check", "Run temp-only visible CDP unconfirmed submission observation regression check"),
    ("visible-cdp-unconfirmed-multi-supplement-followup-check", "Run temp-only visible CDP unconfirmed multi-supplement follow-up regression check"),
    ("pending-visible-cdp-multi-supplement-consumption-check", "Run temp-only pending visible CDP multi-supplement consumption regression check"),
    ("visible-cdp-repeated-unconfirmed-attention-check", "Run temp-only repeated visible CDP unconfirmed submission attention regression check"),
    ("pending-visible-cdp-result-recovery-check", "Run temp-only pending visible CDP result recovery regression check"),
    ("cdp-route-doctor-check", "Run temp-only CDP route maintenance regression checks"),
    ("final-reply-visibility-check", "Run temp-only final reply phone visibility regression checks"),
    ("final-reply-visibility-unconfirmed-check", "Run temp-only final reply visibility-unconfirmed no-resend regression check"),
    ("reply-send-idempotency-check", "Run temp-only status ack and final reply send idempotency regression checks"),
    ("final-reply-media-text-split-check", "Run temp-only final reply text+media split delivery regression check"),
    ("final-reply-media-ret2-governance-check", "Run temp-only final reply ZIP/media ret=-2 governance regression check"),
    ("final-reply-ret2-token-present-diagnostic-check", "Run temp-only ret=-2 context-token-present diagnostic regression check"),
    ("final-reply-active-owner-guard-check", "Run temp-only final reply active-owner guard regression check"),
    ("failed-result-visibility-unconfirmed-recovery-check", "Run temp-only failed-result visibility-unconfirmed recovery regression check"),
    ("push-failed-ret2-fresh-context-recovery-check", "Run temp-only push_failed ret=-2 fresh-context recovery regression check"),
    ("weixin-errcode-session-timeout-check", "Run temp-only errcode=-14 delivery guard regression check"),
    ("reply-dedupe-policy-check", "Run temp-only reply dedupe policy regression checks"),
    ("event-noise-coalescing-check", "Run temp-only diagnostic event coalescing regression checks"),
    ("supplement-final-owner-check", "Run temp-only supplement final-owner regression checks"),
    ("delivery-group-owner-check", "Run temp-only merged delivery group owner regression checks"),
    ("pending-backlog-supplement-batch-check", "Run temp-only pending backlog MCP supplement batching regression check"),
    ("active-visible-cdp-supplement-publish-check", "Run temp-only visible CDP busy MCP supplement publish regression check"),
    ("delivery-group-owner-event-fallback-check", "Run temp-only delivery group owner event fallback regression checks"),
    ("delivery-group-stale-active-snapshot-check", "Run temp-only delivery group stale active snapshot regression check"),
    ("supplement-ack-gating-check", "Run temp-only supplement status acknowledgement regression checks"),
    ("supplement-owner-promotion-check", "Run temp-only supplement-to-owner promotion regression checks"),
    ("orphaned-supplement-promotion-check", "Run temp-only finished-base orphaned supplement promotion regression check"),
    ("waiting-completed-reply-evidence-check", "Run temp-only waiting-owner completed-reply evidence regression check"),
    ("orphaned-supplement-promotion-with-push-evidence-check", "Run temp-only pushed-base orphaned supplement promotion regression check"),
    ("failed-base-supplement-owner-promotion-check", "Run temp-only failed-base supplement owner promotion regression check"),
    ("completed-owner-supplement-ack-window-check", "Run temp-only completed-owner supplement ack window regression check"),
    ("supplement-mcp-disconnect-no-primary-fallback-check", "Run temp-only MCP-down supplement no-primary-fallback regression check"),
    ("supplement-cli-fallback-check", "Run temp-only local stdio MCP supplement fallback regression check"),
    ("supplement-unacked-timeout-release-check", "Run temp-only unacked supplement timeout release regression check"),
    ("supplement-release-no-republish-check", "Run temp-only released supplement no-republish regression check"),
    ("followup-redelivery-mcp-supplement-check", "Run temp-only follow-up redelivery MCP supplement regression check"),
    ("followup-redelivery-fifo-supplement-check", "Run temp-only follow-up FIFO redelivery supplement regression check"),
    ("queued-same-route-supplement-recovery-check", "Run temp-only queued same-route supplement recovery regression check"),
    ("active-runtime-rehydrate-check", "Run temp-only active runtime rehydrate regression check"),
    ("queued-turn-rehydrate-check", "Run temp-only queued started-turn rehydrate regression check"),
    ("queued-turn-materialized-readback-rehydrate-check", "Run temp-only queued unreadable app-server materialized-turn rehydrate regression check"),
    ("supplement-non-owner-host-check", "Run temp-only supplement non-owner host regression check"),
    ("supplement-invalid-published-release-check", "Run temp-only invalid published supplement identity preservation regression check"),
    ("mcp-ack-does-not-complete-owner-check", "Run temp-only MCP ack owner-safety regression check"),
    ("mcp-ack-missing-base-owner-check", "Run temp-only ownerless MCP ack regression check"),
    ("invalid-mcp-ack-not-published-supplement-check", "Run temp-only invalid MCP ack published-supplement guard check"),
    ("followup-redelivery-stale-pending-guard-check", "Run temp-only follow-up stale pending redelivery guard check"),
    ("capability-passphrase-state-machine-check", "Run temp-only capability passphrase state-machine regression checks"),
    ("iteration-closeout-display-check", "Run temp-only iteration proposal closeout-display regression checks"),
    ("app-server-sync-check", "Run temp-only app-server dispatch sync regression checks"),
    ("app-server-unreadable-dispatch-guard-check", "Run temp-only app-server unreadable dispatch guard regression check"),
    ("app-server-unreadable-original-thread-repair-check", "Run temp-only app-server unreadable original-thread repair regression check"),
)


def register_simple_check_commands(subparsers: argparse._SubParsersAction) -> None:
    """Register no-argument bridge check commands."""
    for command_name, help_text in SIMPLE_CHECK_COMMANDS:
        subparsers.add_parser(command_name, help=help_text)
